# Generated by Django 5.2.8 on 2025-11-14 16:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.generate_order_number, editable=False, help_text='Unique order number', max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('express', 'Express (1 hari)'), ('regular', 'Regular (3 hari)')], default='regular', help_text='Type of service: Express or Regular', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of laundry in kg', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per kg for the selected service', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, help_text='Total cost calculated automatically', max_digits=10)),
                ('date_received', models.DateField(default=django.utils.timezone.now, help_text='Date when laundry was received')),
                ('estimated_completion', models.DateField(help_text='Estimated completion date based on service type')),
                ('status', models.CharField(choices=[('diterima', 'Diterima'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('diambil', 'Siap Diambil/Diambil')], default='diterima', help_text='Current status of the order', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the order', null=True)),
                ('storage_deadline', models.DateField(blank=True, help_text='Deadline for customer to pick up completed laundry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Employee who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['date_received'], name='orders_orde_date_re_54249d_idx'), models.Index(fields=['estimated_completion'], name='orders_orde_estimat_851d34_idx')],
            },
        ),
    ]
